// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtW6DYp93hFlsFmE0QA07sBIBnpL183Y0',
    appId: '1:1000350624581:web:072ac37055fefe69d6ec2c',
    messagingSenderId: '1000350624581',
    projectId: 'clifirebase-97106',
    authDomain: 'clifirebase-97106.firebaseapp.com',
    storageBucket: 'clifirebase-97106.appspot.com',
    measurementId: 'G-VBM7YGE4QN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoERgqEqkhTsn9fVv-FJjzbMvnWhXE04c',
    appId: '1:1000350624581:android:a73e44b62aa16f95d6ec2c',
    messagingSenderId: '1000350624581',
    projectId: 'clifirebase-97106',
    storageBucket: 'clifirebase-97106.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWtiOc5VAofAngcvhtP726OC1RxlpwdNQ',
    appId: '1:1000350624581:ios:984e3c60a2d295a8d6ec2c',
    messagingSenderId: '1000350624581',
    projectId: 'clifirebase-97106',
    storageBucket: 'clifirebase-97106.appspot.com',
    iosBundleId: 'com.tech.firebasetagf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWtiOc5VAofAngcvhtP726OC1RxlpwdNQ',
    appId: '1:1000350624581:ios:984e3c60a2d295a8d6ec2c',
    messagingSenderId: '1000350624581',
    projectId: 'clifirebase-97106',
    storageBucket: 'clifirebase-97106.appspot.com',
    iosBundleId: 'com.tech.firebasetagf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtW6DYp93hFlsFmE0QA07sBIBnpL183Y0',
    appId: '1:1000350624581:web:e99fd895ba9cd185d6ec2c',
    messagingSenderId: '1000350624581',
    projectId: 'clifirebase-97106',
    authDomain: 'clifirebase-97106.firebaseapp.com',
    storageBucket: 'clifirebase-97106.appspot.com',
    measurementId: 'G-NT80B02BYV',
  );
}
